### ISSUE TITLE
ConfigureCQELight() cannot use environment variables from a docker-compose.yaml file

### ISSUE THREAD

**Issue by rvaquette** [hybrid-technologies-solutions/CQELight#499]
When calling ConfigureCQELight(), only environment variables defined into the appsettings*.json files can be used.
When using CQELight in an application deployed using docker compose, the environment variables defined into the .yml file cannot be used at that point.

**Comment by hybrid-technologies-solutions** [comment]
Thank you for reporting the issue.

Indeed, we've never tried such a configuration loading and we mainly focused on appsettings, as it is the standard way of loading configuration.

Can you provide us a little repro sample on github to try it and fix it ? (or a PR if you already know how to fix it)

In the meantime, as a workaround, you may try to load it manually in the ConfigureCQELight lambda in your Program.cs.

We'll look at fixing it in next patch release.

**Comment by rvaquette** [comment]
In fact in Program.cs the settings that are available are those defined in the appsettings files.
The full configuration (using environment variables) is available into the Startup.cs, it's "by design" I suppose in ASP.Net (Core).

These steps can permit you to reproduce the problem:
1) create an simple API ASPNET Core project in Visual Studio
2) do a right click on the project > Add > Container Orchestrator Support
3) in the new docker-compose project, into docker-compose.override.yml, define an environement variable for your project, as :
  catalog.api:
    environment:
      - "EventBus:HostName=eventbus"

4) when debugging the project, you'll see that the "EventBus:HostName" is not known into Program.cs, but it is into Startup.cs !...

Merci d'avance pour votre aide !!!

**Comment by hybrid-technologies-solutions** [comment]
So I guess this is not an issue for ASP.NET Core 2.1, as the way to configure CQELight is done in Startup.cs

I'll check for ASP.NET Core 3.1 and update this thread !

**Comment by hybrid-technologies-solutions** [comment]
The issue has been fixed and will be in the next release.

However, you can't use semicolons (" : ") in your environment key like you texted before because it makes variable failed to be retrieved. You have to replace semicolon by double underscore : 

```
catalog.api:
  environment:
    - "EventBus__HostName=eventbus"
```
When doing so, you can now use conf["EventBus:HostName"] in Program.cs on an ASP.NET Core 3.1 web app.

A fix will be released very soon.

Thank you again for reporting issue.

Note : if this is a blocking issue for you and you want the fix directly without waiting for stable release, you can download preview version from our public preview registry : https://registry.hybrid-technologies-solutions.com/repository/cqelight-prev/
